CREATE TABLE code_type (
  code_id INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
  code_name VARCHAR NOT NULL,
);

CREATE TABLE post (
  post_id INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
  code_id INTEGER UNSIGNED NOT NULL,
  type_id INTEGER UNSIGNED NOT NULL,
  user_id INTEGER UNSIGNED NOT NULL,
  rank_id INTEGER UNSIGNED NULL,
  level_id INTEGER UNSIGNED NOT NULL,
  post TEXT NULL,
  name VARCHAR NULL,
  date_create INTEGER UNSIGNED NULL,
  last_mod INTEGER UNSIGNED NULL,
);

CREATE TABLE post_comment (
  post_id INTEGER UNSIGNED NOT NULL,
  user_id INTEGER UNSIGNED NOT NULL,
  date_create INTEGER UNSIGNED NULL,
  last_mod INTEGER UNSIGNED NULL,
  comment_2 TEXT NULL,
);

CREATE TABLE post_level (
  level_id INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
  level VARCHAR NULL,
  description TEXT NULL,
);

CREATE TABLE post_rank (
  rank_id INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
  rank VARCHAR NULL,
);

CREATE TABLE post_type (
  type_id INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
  type_2 VARCHAR NULL,
);

CREATE TABLE users (
  user_id INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
  user_level_id INTEGER UNSIGNED NOT NULL,
  status_id INTEGER UNSIGNED NOT NULL,
  username INTEGER UNSIGNED NULL,
  pass INTEGER UNSIGNED NULL,
  last_login INTEGER UNSIGNED NULL,
  last_ip INTEGER UNSIGNED NULL,
  register_time INTEGER UNSIGNED NULL,
);

CREATE TABLE user_ban (
  user_id INTEGER UNSIGNED NOT NULL,
  ban_time INTEGER UNSIGNED NULL,
  ban_by INTEGER UNSIGNED NULL,
  reason TEXT NULL,
);

CREATE TABLE user_level (
  user_level_id INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
  level VARCHAR NULL,
);

CREATE TABLE user_status (
  status_id INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
  status_2 VARCHAR NULL,
);


